spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/IdeaProjects/TIL/programming/jpa-shop/h2/database
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # sout
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug # logger

